### ISSUE TITLE
RegisterModal.js - Checking if the email already exists in firebase and firebase error

### ISSUE THREAD

**Issue by shuetyi-lee** [haozoo/recipe-book#9]
The Register Modal currently only checks if the email's expression is valid but does not check if it already exists in firebase. We need to check if the email already exists and change the error message accordingly.

When I tried to sign up as a new user with a new set of email, password and username, firebase showed this error `Firebase: Error (auth/internal-error)` and I am not able to resolve it.

**Comment by haozoo** [comment]
Issue fixed in [commit](https://github.com/haozoo/recipe-book/commit/e1f3cfda36bac4d033e2c6c067f6e305c5bd6eb9). Occurred as email/password was not being passed into the authentication functions.
